# edw_data.R

#' Read EDW data from csv files
#'
#' \code{read_edw_data} takes a directory and file name and reads in all
#' matching csv files and binds them together into a data frame
#'
#' This function takes a directory and file name and reads in all
#' matching csv files and binds them together into a data frame.
#'
#'
#' @param data.dir A character vector with the name of the directory containing
#'   the data files
#' @param pattern A character vector with name of data file
#'
#' @return A data frame
#'
#' @import dplyr
#'
#' @export
read_edw_data <- function(data.dir, pattern) {

    list.files(data.dir, pattern = pattern, full.names = TRUE) %>%
        lapply(read.csv, colClasses = "character") %>%
        bind_rows %>%
        distinct
}


#' Tidy data from EDW
#'
#' \code{tidy_edw_data} takes a data frame with raw data from EDW and returns a
#' tidied data frame
#'
#' This function takes a data frame with raw data generated by an EDW query, and
#' a character vector indicating the type of data being tidied, and will return
#' a tidied data frame. Valid options for type include: blood, demographics,
#' diagnosis, ht_wt, home_meds, icu_score, labs_cbc, labs_chemistry, labs_coag,
#' labs_hit, labs_lft, labs_preg, labs_renal, location, meds_cont, meds_sched,
#' mpp, procedure, surgery, radiology, vent, vitals, warfarin.
#'
#'
#' @param raw.data A data frame with raw data from EDW
#' @param type A character vector indicating the type of data being tidied
#'
#' @return A data frame
#'
#' @import dplyr
#'
#' @export
tidy_edw_data <- function(raw.data, type) {

    if (type == "blood") {

    } else if (type == "demographics") {
        tidy.data <- raw.data %>%
            distinct %>%
            transmute(pie.id = PowerInsight.Encounter.Id,
                   person.id = Person.ID,
                   age = as.numeric(Age..Years..Visit.),
                   sex = factor(Sex, exclude = c("", "Unknown")),
                   race = factor(Race, exclude = c("", "Unknown")),
                   disposition = factor(Discharge.Disposition),
                   los = as.numeric(LOS..Actual.),
                   visit.type = factor(Encounter.Type))

    } else {
        print("Invalid type")
        return(NULL)
    }
    return(tidy.data)
}

