# edw_data.R

#' Read EDW data from csv files
#'
#' \code{read_edw_data} takes a directory and file name and reads in all
#' matching csv files and binds them together into a data frame
#'
#' This function takes a directory and file name and reads in all
#' matching csv files and binds them together into a data frame.
#'
#'
#' @param data.dir A character with the name of the directory containing the
#'   data files
#' @param pattern A character with name of data file or pattern to match
#' @param type An optional character indicating type of data being tidied
#'
#' @return A data frame
#'
#' @import dplyr
#'
#' @export
read_edw_data <- function(data.dir, file.name, type = NA) {
    # if type is NA, then set type to file.name
    if (is.na(type)) {
        type <- file.name
    }

    raw <- read_data(data.dir, file.name)

    tidy <- tidy_edw_data(raw, type)

    return(tidy)
}

#' Read and join data from multiple csv files
#'
#' \code{read_data} takes a directory and file name and reads in all matching
#' csv files and binds them together into a data frame
#'
#' This function takes a directory and file name and reads in all matching csv
#' files and binds them together into a data frame.
#'
#' @param data.dir A character with the name of the directory containing the
#'   data files
#' @param pattern A character with name of data file or pattern to match
#'
#' @return A data frame
#'
#' @import dplyr
#'
#' @export
read_data <- function(data.dir, file.name) {
    raw <- list.files(data.dir, pattern = file.name, full.names = TRUE) %>%
        lapply(read.csv, colClasses = "character") %>%
        bind_rows %>%
        distinct

    return(raw)
}

#' Tidy data from EDW
#'
#' \code{tidy_edw_data} takes a data frame with raw data from EDW and returns a
#' tidied data frame
#'
#' This function takes a data frame with raw data generated by an EDW query, and
#' a character vector indicating the type of data being tidied, and will return
#' a tidied data frame. Valid options for type include: blood, demographics,
#' diagnosis, home_meds, icu_score, labs, location, measures, meds_continuous,
#' meds_freq, meds_sched, meds_sched_freq, mpp, procedures, surgeries,
#' radiology, vent, vitals, warfarin.
#'
#'
#' @param raw.data A data frame with raw data from EDW
#' @param type A character vector indicating the type of data being tidied
#'
#' @return A data frame
#'
#' @import dplyr
#'
tidy_edw_data <- function(raw.data, type) {

    if (type == "blood") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               blood.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               blood.prod = Clinical.Event,
                               blood.type = factor(Clinical.Event.Result))

    } else if (type == "demographics") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                   person.id = Person.ID,
                   age = as.numeric(Age..Years..Visit.),
                   sex = factor(Sex, exclude = c("", "Unknown")),
                   race = factor(Race, exclude = c("", "Unknown")),
                   disposition = factor(Discharge.Disposition),
                   los = as.numeric(LOS..Actual.),
                   visit.type = factor(Encounter.Type))

    } else if (type == "diagnosis") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               diag.code = ICD9.Diagnosis.Code,
                               diag.type = factor(Diagnosis.Type, exclude = ""),
                               diag.seq = factor(Diagnosis.Code.Sequence))

    } else if (type == "home_meds") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               med = Order.Catalog.Short.Description,
                               order.name = Order.Catalog.Mnemonic,
                               med.type = factor(Orig.Orderable.Type.Flag.Desc))

    } else if (type == "labs") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               lab.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               lab = Clinical.Event,
                               lab.result = Clinical.Event.Result)

    } else if (type == "measures") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               measure.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               measure = Clinical.Event,
                               measure.result = as.numeric(Clinical.Event.Result),
                               measure.units = factor(Clinical.Event.Result.Units))

    } else if (type == "meds_continuous") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               med.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               med = Clinical.Event,
                               med.rate = as.numeric(Infusion.Rate),
                               med.rate.units = factor(Infusion.Rate.Unit, exclude = ""),
                               event.id = Event.ID)

    } else if (type == "meds_sched") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               med.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               med = Clinical.Event,
                               med.dose = as.numeric(Dosage.Amount),
                               med.dose.units = factor(Dosage.Unit, exclude = ""),
                               med.route = factor(Route.of.Administration...Short, exclude = ""),
                               event.id = Event.ID)

    } else if (type == "meds_sched_freq") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               med.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               med = Clinical.Event,
                               med.dose = as.numeric(Dosage.Amount),
                               med.dose.units = factor(Dosage.Unit, exclude = ""),
                               med.route = factor(Route.of.Administration...Short, exclude = ""),
                               freq = Parent.Order.Frequency.Description,
                               event.id = Event.ID)

    } else if (type == "procedures") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               proc.date = lubridate::ymd_hms(Procedure.Date.and.Time),
                               proc.code = ICD9.Procedure.Code)

    } else if (type == "radiology") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               rad.datetime = lubridate::ymd_hms(Clinical.Event.End.Date.Time),
                               rad.type = Clinical.Event)

    } else if (type == "surgeries") {
        tidy.data <- transmute(raw.data, pie.id = PowerInsight.Encounter.Id,
                               surg.start.datetime = lubridate::ymd_hms(Start.Date.Time),
                               surg.stop.datetime = lubridate::ymd_hms(Stop.Date.Time),
                               surgery = Procedure,
                               add.on = ifelse(Add.On.Indicator == 1, TRUE, FALSE),
                               asa.class = factor(ASA.Class, exclude = ""),
                               primary.proc = ifelse(Primary.Procedure.Indicator == 1, TRUE, FALSE))

    } else {
        print("Invalid type")
        return(NULL)
    }
    return(tidy.data)
}

